### PR TITLE
Increase max build time

### PR DESCRIPTION
**Pull request by ad-m**

### CODE REVIEW

**Comment by bernardobelchior** [comment]
[Reference](https://docs.aws.amazon.com/lambda/latest/dg/limits.html)

**Comment by chuckoy** [comment]
Worth noting that memory limit has been doubled to 3GB as well https://docs.aws.amazon.com/lambda/latest/dg/limits.html, you could merge both in the same PR 😁

**Comment by enriquemanuel** [comment]
there are 2 PR's for the same thing and it not only increased the time but the memory, and that was noted in PR #113

**Comment by mhart** [comment]
Updated this in Jun and Oct in the 0.10.0 branch – will hopefully merge this over the holidays!

https://github.com/lambci/lambci/blob/version-0.10.0/README.md

**Pull request closed without merging**
