### PR TITLE
bump git to 2.4.12

### LINKED ISSUE #93: Bump git to 2.14.2
The shipped git is out of date, and possibly insecure. I'd like to bump the shipped version to 2.14.2. I'll be submitting a PR with that change, but I wanted to check the process to recompile git.

I've performed the following steps:

#### Setup
- Bring up an Amazon Linux instance
-  `sudo yum groupinstall "Development Tools"`
- `sudo yum install git`
- `mkdir ~/install`
- `mkdir ~/discard`

#### openssh

- `git clone https://github.com/openssh/openssh-portable.git`
- Comment `sshconnect.h` per https://github.com/lambci/lambci/issues/26#issuecomment-274876986
- `sudo yum install openssl-devel`
- `sudo yum install perl-devel`
- run `autoreconf`
- `./configure --prefix=$HOME/install --sysconfdir=$HOME/discard --sbindir=$HOME/discard --mandir=$HOME/discard`
- `make`
- `make install`
- cd

#### Git

- `wget https://www.kernel.org/pub/software/scm/git/git-2.14.2.tar.xz`
- `tar xf git-2.14.2.tar.xz`
- `cd git-2.14.2`
- `./configure --prefix=$HOME/install --mandir=$HOME/discard --htmldir=$HOME/discard --infodir=$HOME/discard --without-tcltk`
- `make`
- `make install`

Then , tar up `~/install` and drop it into the `vendor` directory.

Any comments, things I missed, or extra things that should be done?

### PR DESCRIPTION
**Pull request by cjs**
This fixes #93 which is where the process I followed to generate this file is laid out. If this works, I'll open another PR to document the process.

### CODE REVIEW

**Comment by cjs** [comment]
FWIW I tested this in a LambCI environment deployed off of this branch (https://rfa-lambci-buildresults-6htgm00tc7hm.s3.us-east-2.amazonaws.com/gh/cjs/lambci/builds/1/6f8d6a5f3a66083724727ad0d58eef51.html) , and it worked.

**Comment by mhart** [comment]
Hi @cjs! Thanks for doing this, but unfortunately the git tarball is much larger than the existing one (85MB vs 17MB)

I'll look at updating git to the latest Amazon Linux version

**Comment by cjs** [comment]
@mhart I compiled from the git/openssh upstream sources as opposed to the Amazon Linux versions, and from the looks of it I installed portions that weren't included in your original. If you have rough notes on exactly how you created the tarball originall, I can redo it and take the time to document the process. 

Otherwise, I'm happy to close this if you'd rather control the binary creation process. In retrospect, that might be a good idea since you're shipping binaries that other people are depending on. However, it would be nice to at least have the process documented .

**Comment by mhart** [comment]
Agreed – process should definitely be documented 👍 

I have some rough notes on how I created the git tarball, but I'll get them into shape first – and make sure they still work!

Should be able to tackle this tomorrow

**Comment by defionscode** [comment]
@mhart did you ever whip up those notes?

**Comment by mhart** [comment]
@defionscode you can see here (at least for v2.13.5): https://github.com/lambci/lambci/tree/version-0.10.0/build/git

**Pull request closed without merging**
